# Author config
# 作者配置

name = "Dvesti"
email = "vladimir.dmitrijev@outlook.com"
link = "https://github.com/dvesti"
avatar = "/images/avatar.webp"
gravatarEmail = "vladimir.dmitrijev@outlook.com"
