baseURL: https://dve.netlify.app
defaultContentLanguage: en
title: DoIt
enableRobotsTXT: yes
enableGitInfo: yes
enableEmoji: yes
theme: DoIt

markup:
  goldmark:
    renderer:
      unsafe: true
