baseURL: https://dve.netlify.app
defaultContentLanguage: ru
title: Bolt
enableRobotsTXT: yes
enableGitInfo: yes
enableEmoji: yes
theme: DoIt
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]

markup:
  goldmark:
    renderer:
      unsafe: true
      
pagination:
  disableAliases: false
  pagerSize: 10
  path: page
  
